class Deck:
    """
    has list of 52 cards each a dict with name, suit keys
    """
    def __init__(self):
        self.Cards = [{'name': 'Ace', 'suit': 'Spades'},
                      {'name': 'Ace', 'suit': 'Clubs'},
                      {'name': 'Ace', 'suit': 'Hearts'},
                      { 'name': 'Ace', 'suit': 'Diamonds'},
                      {'name': 'Two', 'suit': 'Spades'},
                      {'name': 'Two', 'suit': 'Clubs'},
                      {'name': 'Two', 'suit': 'Hearts'},
                      {'name': 'Two', 'suit': 'Diamonds'},
                      {'name': 'Three', 'suit': 'Spades'},
                      {'name': 'Three', 'suit': 'Clubs'},
                      {'name': 'Three', 'suit': 'Hearts'},
                      {'name': 'Three', 'suit': 'Diamonds'},
                      {'name': 'Four', 'suit': 'Spades'},
                      {'name': 'Four', 'suit': 'Clubs'},
                      {'name': 'Four', 'suit': 'Hearts'},
                      { 'name': 'Four', 'suit': 'Diamonds'},
                      {'name': 'Five', 'suit': 'Spades'},
                      {'name': 'Five', 'suit': 'Clubs'},
                      {'name': 'Five', 'suit': 'Hearts'},
                      { 'name': 'Five', 'suit': 'Diamonds'},
                      {'name': 'Six', 'suit': 'Spades'},
                      {'name': 'Six', 'suit': 'Clubs'},
                      {'name': 'Six', 'suit': 'Hearts'},
                      { 'name': 'Six', 'suit': 'Diamonds'},
                      {'name': 'Seven', 'suit': 'Spades'},
                      {'name': 'Seven', 'suit': 'Clubs'},
                      {'name': 'Seven', 'suit': 'Hearts'},
                      { 'name': 'Seven', 'suit': 'Diamonds'},
                      {'name': 'Eight', 'suit': 'Spades'},
                      {'name': 'Eight', 'suit': 'Clubs'},
                      {'name': 'Eight', 'suit': 'Hearts'},
                      { 'name': 'Eight', 'suit': 'Diamonds'},
                      {'name': 'Nine', 'suit': 'Spades'},
                      {'name': 'Nine', 'suit': 'Clubs'},
                      {'name': 'Nine', 'suit': 'Hearts'},
                      { 'name': 'Nine', 'suit': 'Diamonds'},
                      {'name': 'Ten', 'suit': 'Spades'},
                      {'name': 'Ten', 'suit': 'Clubs'},
                      {'name': 'Ten', 'suit': 'Hearts'},
                      { 'name': 'Ten', 'suit': 'Diamonds'},
                      {'name': 'Jack', 'suit': 'Spades'},
                      {'name': 'Jack', 'suit': 'Clubs'},
                      {'name': 'Jack', 'suit': 'Hearts'},
                      { 'name': 'Jack', 'suit': 'Diamonds'},
                      {'name': 'Queen', 'suit': 'Spades'},
                      {'name': 'Queen', 'suit': 'Clubs'},
                      {'name': 'Queen', 'suit': 'Hearts'},
                      {'name': 'Queen', 'suit': 'Diamonds'},
                      {'name': 'King', 'suit': 'Spades'},
                      {'name': 'King', 'suit': 'Clubs'},
                      {'name': 'King', 'suit': 'Hearts'},
                      { 'name': 'King', 'suit': 'Diamonds'}]
